version: 2

project_name: falcon

before:
  hooks:
    - go mod tidy
    - go build ./...

builds:
  - id: falcon
    main: ./cmd/falcon
    binary: falcon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: blackcoderx
    name: falcon
  draft: false
  prerelease: auto
  skip_upload: false
  name_template: "Falcon v{{.Version}}"
  header: |
    ## Falcon v{{.Version}}

    AI-powered API debugging that understands your codebase.
  footer: |
    ---

    **Full Changelog**: https://github.com/blackcoderx/falcon/compare/{{ .PreviousTag }}...{{ .Tag }}
